""" 
     
""" 
 
UFCODER_ERROR_CODES = {
    0x00 :'UFR_OK',
    0x01 :'UFR_COMMUNICATION_ERROR',
    0x02 :'UFR_CHKSUM_ERROR',
    0x03 :'UFR_READING_ERROR',
    0x04 :'UFR_WRITING_ERROR',
    0x05 :'UFR_BUFFER_OVERFLOW',
    0x06 :'UFR_MAX_ADDRESS_EXCEEDED',
    0x07 :'UFR_MAX_KEY_INDEX_EXCEEDED',
    0x08 :'UFR_NO_CARD',
    0x09 :'UFR_COMMAND_NOT_SUPPORTED',
    0x0A :'UFR_FORBIDEN_DIRECT_WRITE_IN_SECTOR_TRAILER',
    0x0B :'UFR_ADDRESSED_BLOCK_IS_NOT_SECTOR_TRAILER',
    0x0C :'UFR_WRONG_ADDRESS_MODE',
    0x0D :'UFR_WRONG_ACCESS_BITS_VALUES',
    0x0E :'UFR_AUTH_ERROR',
    0x0F :'UFR_PARAMETERS_ERROR',
    0x10 :'UFR_MAX_SIZE_EXCEEDED',

    0x70 :'UFR_WRITE_VERIFICATION_ERROR',
    0x71 :'UFR_BUFFER_SIZE_EXCEEDED',
    0x72 :'UFR_VALUE_BLOCK_INVALID',
    0x73 :'UFR_VALUE_BLOCK_ADDR_INVALID',
    0x74 :'UFR_VALUE_BLOCK_MANIPULATION_ERROR',
    0x75 :'UFR_WRONG_UI_MODE',
    0x76 :'UFR_KEYS_LOCKED',
    0x77 :'UFR_KEYS_UNLOCKED',
    0x78 :'UFR_WRONG_PASSWORD',
    0x79 :'UFR_CAN_NOT_LOCK_DEVICE',
    0x7A :'UFR_CAN_NOT_UNLOCK_DEVICE',
    0x7B :'UFR_DEVICE_EEPROM_BUSY',
    0x7C :'UFR_RTC_SET_ERROR',
    
    0x80: 'UFR_WRONG_NDEF_CARD_FORMAT',
    0x81: 'UFR_NDEF_MESSAGE_NOT_FOUND',

    0x50 :'UFR_COMMUNICATION_BREAK',
    0x51 :'UFR_NO_MEMORY_ERROR',
    0x52 :'UFR_CAN_NOT_OPEN_READER',
    0x53 :'UFR_READER_NOT_SUPPORTED',
    0x54 :'UFR_READER_OPENING_ERROR',
    0x55 :'UFR_READER_PORT_NOT_OPENED',
    0x56 :'UFR_CANT_CLOSE_READER_PORT',

    0xA0 :'UFR_FT_STATUS_ERROR_1',
    0xA1 :'UFR_FT_STATUS_ERROR_2',
    0xA2 :'UFR_FT_STATUS_ERROR_3',
    0xA3 :'UFR_FT_STATUS_ERROR_4',
    0xA4 :'UFR_FT_STATUS_ERROR_5',
    0xA5 :'UFR_FT_STATUS_ERROR_6',
    0xA6 :'UFR_FT_STATUS_ERROR_7',
    0xA7 :'UFR_FT_STATUS_ERROR_8',
    0xA8 :'UFR_FT_STATUS_ERROR_9',

    0x3E8: 'Undocummented error',
    0x3E9: 'Undocummented error',

    0xFFFFFFFF :'MAX_UFR_STATUS',
    
    # JC cards APDU error code
    0xAE: 'UFR_APDU_TRANSCEIVE ERROR',
    0x6000 : 'UFR_APDU_JC_APP_NOT_SELECTED',
    0x6001 : 'UFR_APDU_JC_APP_BUFF_EMPTY',
    0x6002 : 'UFR_APDU_WRONG_SELECT_RESPOSNSE',
    0x6003 : 'UFR_APDU_WRONG_KEY_TYPE',
    0x6004 : 'UFR_APDU_WRONG_KEY_SIZE',
    0x6005 : 'UFR_APDU_WRONK_KEY_PARAMS',
    0x6006 : 'UFR_APDU_WRONG_SIGNING_ALGORITHM',
    0x6007 : 'UFR_APDU_PLAIN_TEXT_MAX_SIZE_EXCEEDED',
    0x6008 : 'UFR_APDU_UNSUPPORTED_KEY_SIZE',
    0x6009 : 'UFR_APDU_UNSUPPORTED_ALGORITHMS',
    0x600A : 'UFR_APDU_PKI_OBJECT_NOT_FOUND',
    
    # ISO7816-4 Errors (R-APDU) - 2 SW bytes returned by the card, prefixed with 0x000A:
    0x000A0000 : 'UFR_APDU_SW_TAG',
    0x000A6700 : 'UFR_APDU_SW_WRONG_LENGTH',
    0x000A6982 : 'UFR_APDU_SW_SECURITY_STATUS_NOT_SATISFIED',
    0x000A6983 : 'UFR_APDU_SW_AUTHENTICATION_METHOD_BLOCKED',
    0x000A6984 : 'UFR_APDU_SW_DATA_INVALID',
    0x000A6985 : 'UFR_APDU_SW_CONDITIONS_NOT_SATISFIED',
    0x000A6A80 : 'UFR_APDU_SW_WRONG_DATA',
    0x000A6A82 : 'UFR_APDU_SW_FILE_NOT_FOUND',
    0x000A6A83 : 'UFR_APDU_SW_RECORD_NOT_FOUND',
    0x000A6A88 : 'UFR_APDU_SW_DATA_NOT_FOUND',
    0x000A6A89 : 'UFR_APDU_SW_ENTITY_ALREADY_EXISTS',
    0x000A6D00 : 'UFR_APDU_SW_INS_NOT_SUPPORTED',
    0x000A6F00 : 'UFR_APDU_SW_NO_PRECISE_DIAGNOSTIC'

}

####################################################################

DESFIRE_ERROR_CODES = {
    
    0xBB7  : 'READER_ERROR',                    #// 2999 [dec]
    0xBB8  : 'NO_CARD_DETECTED',                    #// 3000 [dec]
    0xBB9  : 'CARD_OPERATION_OK',               #// 3001 [dec]
    0xBBA  : 'WRONG_KEY_TYPE',                  #// 3002 [dec]
    0xBBB  : 'KEY_AUTH_ERROR',                  #// 3003 [dec]
    0xBBC  : 'CARD_CRYPTO_ERROR',           #// 3004 [dec]
    0xBBD  : 'READER_CARD_COMM_ERROR',          #// 3005 [dec]
    0xBBE  : 'PC_READER_COMM_ERROR',            #// 3006 [dec]
    0xBBF  : 'COMMIT_TRANSACTION_NO_REPLY',    #// 3007 [dec]
    0x0BC0 : 'COMMIT_TRANSACTION_ERROR',        #// 3008 [dec]
    0x0C0C : 'DESFIRE_CARD_NO_CHANGES',
    0x0C03 : 'DESFIRE_CARD_OUT_OF_EEPROM_ERROR',
    0x0C1C : 'DESFIRE_CARD_ILLEGAL_COMMAND_CODE',
    0x0C1E : 'DESFIRE_CARD_INTEGRITY_ERROR',
    0x0C40 : 'DESFIRE_CARD_NO_SUCH_KEY',
    0x0C7E : 'DESFIRE_CARD_LENGTH_ERROR',
    0x0C9D : 'DESFIRE_CARD_PERMISSION_DENIED',
    0x0C93 : 'DESFIRE_CARD_PARAMETER_ERROR',
    0x0CA0 : 'DESFIRE_CARD_APPLICATION_NOT_FOUND',
    0x0CA1 : 'DESFIRE_CARD_APPL_INTEGRITY_ERROR',
    0x0CAE : 'DESFIRE_CARD_AUTHENTICATION_ERROR',
    0x0CAF : 'DESFIRE_CARD_ADDITIONAL_FRAME',
    0x0CBE : 'DESFIRE_CARD_BOUNDARY_ERROR',
    0x0CC1 : 'DESFIRE_CARD_PICC_INTEGRITY_ERROR',
    0x0CCA : 'DESFIRE_CARD_COMMAND_ABORTED',
    0x0CCD : 'DESFIRE_CARD_PICC_DISABLED_ERROR',
    0x0CCE : 'DESFIRE_CARD_COUNT_ERROR',
    0x0CDE : 'DESFIRE_CARD_DUPLICATE_ERROR',
    0x0CEE : 'DESFIRE_CARD_EEPROM_ERROR_DES',
    0x0CF0 : 'DESFIRE_CARD_FILE_NOT_FOUND',
    0x0CF1 : 'DESFIRE_CARD_FILE_INTEGRITY_ERROR', 
}